sudo: true
language: python

os:
 - linux

python:
  - "2.7"

global:
  env:
    - COMMIT_AUTHOR_EMAIL: "f.zapata@esciencecenter.nl"

install:
  # install library
  - pip install numpy scipy
  - pip install .[test]

script:
  - (cd tests && coverage run -m unittest discover -vvv)

branches:
  only:
    - master
